python3-pip: ensure pickle is installed
pip3 depends on pickle, so add python3-pickle to RDEPENDS.
Without it, errors such as the following occur:

>>> import pip._internal
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File "/usr/lib64/python3.7/site-packages/pip/internal/init_.py", line 40, in <module>
from pip._internal.cli.autocompletion import autocomplete
File "/usr/lib64/python3.7/site-packages/pip/_internal/cli/autocompletion.py", line 8, in <module>
from pip._internal.cli.main_parser import create_main_parser
File "/usr/lib64/python3.7/site-packages/pip/_internal/cli/main_parser.py", line 7, in <module>
from pip._internal.cli import cmdoptions
File "/usr/lib64/python3.7/site-packages/pip/_internal/cli/cmdoptions.py", line 29, in <module>
from pip._internal.utils.ui import BAR_TYPES
File "/usr/lib64/python3.7/site-packages/pip/_internal/utils/ui.py", line 16, in <module>
from pip._internal.utils.logging import get_indentation
File "/usr/lib64/python3.7/site-packages/pip/_internal/utils/logging.py", line 6, in <module>
import logging.handlers
File "/usr/lib64/python3.7/logging/handlers.py", line 26, in <module>
import logging, socket, os, pickle, struct, time, re
ModuleNotFoundError: No module named 'pickle'

(From OE-Core rev: ac040230c5b6dd166f248ba87d80f55e8b299dce)

Signed-off-by: Trevor Gamblin <trevor.gamblin@windriver.com>
Signed-off-by: Richard Purdie <richard.purdie@linuxfoundation.org>