rust: Upgrade 1.85.1->1.86.0
* Added "pkgconfig-native" for native build to resolve openssl-sys crate
dependency on pkg-config.

* Disable ninja build which caused regression for bootstrap build.

* Add do_install:append() task to remove cargo bin from rust native builds.
This resolves the following conflict:

ERROR: libstd-rs-1.86.0-r0 do_prepare_recipe_sysroot: The file /usr/bin/cargo is
installed by both rust-native and cargo-native, aborting

* Update Unicode-3.0 license checksums.

* The "remote-test-server" bin is now generated in stage2-tools-bin dir.
  Update the test suite accordingly.

* Rebase and update rust-oe-selftest.patch file with v1.86.0.

* Add the following dependencies during rust build.

  pkgconfig-native, openssl, bash: These were included as openssl-sys crate require it.

  Pack zsh to fix:
  do_package: QA Issue: rust: Files/directories were installed but not shipped in any package:
  /usr/share/zsh
  /usr/share/zsh/site-functions
  /usr/share/zsh/site-functions/_cargo
  Please set FILES such that these items are packaged. Alternatively if they are unneeded,
  avoid installing them or delete them within do_install

* Add ldflags to INSANE_SKIP to fix:
  do_package_qa: QA Issue: File /usr/lib/rustlib/x86_64-poky-linux-gnu/bin/rust-lld
  in package rust doesn't have GNU_HASH (didn't pass LDFLAGS?) [ldflags]

* Install "llvm-tblgen" from native-sysroot to recipe sysroot to handle
  file not found error in building llvm-rust:
  /bin/sh: line 1:/home/poky/build/tmp/work/core2-64-poky-linux/rust/1.86.0/recipe-sysroot/usr/lib/llvm-rust/bin/llvm-tblgen:
  No such file or directory

  | make[2]: *** [COFF/CMakeFiles/COFFOptionsTableGen.dir/build.make:120: COFF/Options.inc] Error 127
  | make[1]: *** [CMakeFiles/Makefile2:630: COFF/CMakeFiles/COFFOptionsTableGen.dir/all] Error 2
  | make[1]: *** Waiting for unfinished jobs....

  (Note: I am not sure if this is the correct approach to fix this. This
  works for when "host == target" machine, but breaks again for
  cross-compilation builds or nativesdk builds. Any suggestions/inputs are
  welcomed.

  Also, checked with specifying the tblgen path in oecmake in rust recipe,
  EXTRA_OECMAKE:append:class-target = "\
       -DLLVM_TABLEGEN=${STAGING_LIBDIR_NATIVE}/llvm-rust/bin/llvm-tblgen \
  but still got the same error.)

* Some patches were causing rebase conflicts after the upgrade.
They are temporarily dropped. They will be included again
once the rust build issues are resolved.

Signed-off-by: Yash Shinde <Yash.Shinde@windriver.com>
Signed-off-by: Harish Sadineni <Harish.Sadineni@windriver.com>