python3-cryptography{-vectors}: upgrade 39.0.2 -> 40.0.2
* Refresh patches
* Update python3-crytography-crates.inc

WIP:
Currently fails in do_compile of cryptogrpahy-rust:
|   cargo:warning=.../build/tmp/work/core2-64-poky-linux/python3-cryptography/40.0.2-r0/build/target/x86_64-poky-linux-gnu/release/build/cryptography-rust-aa00e39a952c07ee/out/_openssl.c:57:10: fatal error: Python.h: No such file or directory
|   cargo:warning=   57 | #include <Python.h>
|   cargo:warning=      |          ^~~~~~~~~~
|   cargo:warning=compilation terminated.
|   exit status: 1
|
|   --- stderr

Breaking changes:

BACKWARDS INCOMPATIBLE: As announced in the 39.0.0 changelog, the way
cryptography links OpenSSL has changed. This only impacts users who build
cryptography from source (i.e., not from a wheel), and specify their own
version of OpenSSL. For those users, the CFLAGS, LDFLAGS, INCLUDE, LIB,
and CRYPTOGRAPHY_SUPPRESS_LINK_FLAGS environment variables are no longer
valid. Instead, users need to configure their builds as documented here [1].

For details of changes, see:
https://cryptography.io/en/latest/changelog/#v40-0-0
https://cryptography.io/en/latest/changelog/#v40-0-1
https://cryptography.io/en/latest/changelog/#v40-0-2

[1] https://docs.rs/openssl/latest/openssl/#automatic

Signed-off-by: Tim Orling <tim.orling@konsulko.com>