ruby: workaround ptest hang problem
since openssl 3 not compatible problem, ruby have disable openssl
extention. But disable openssl extention make test_smtp.rs hang at
test case "test_start".

Net::TestSMTP#test_start:
NameError: uninitialized constant Net::SMTP::OpenSSL
Did you mean? Open3
/usr/lib64/ruby/3.0.0/net/smtp.rb:195:in `default_ssl_context'
/usr/lib64/ruby/3.0.0/net/smtp.rb:552:in `start'
/usr/lib64/ruby/3.0.0/net/smtp.rb:475:in `start'
/usr/lib64/ruby/ptest/test/net/smtp/test_smtp.rb:199:in `test_start'

temporarily remove the hang case to make other testcases can be run.

(From OE-Core rev: 619baa7e374d8565a8c43680273f78939ef1c422)

Signed-off-by: Changqing Li <changqing.li@windriver.com>
Signed-off-by: Richard Purdie <richard.purdie@linuxfoundation.org>