metadata.py: return info after fallback methods
If python3 git module is not installed, we fall back to some git
command to get info. A previous commit (b8d22ed6) accidently deleted
the return statement, causing errors like below.

  Exception: UnboundLocalError: local variable 'InvalidGitRepositoryError' referenced before assignment

Signed-off-by: Chen Qi <Qi.Chen@windriver.com>