classes/sstate.bbclass: checkhashes modify to take into account siginfo.
When sstate file exists but not siginfo one then sstate need to be marked as
 non-available to avoid post FetchError's when trying to download siginfo.

For example,

   WARNING: Failed to fetch URL
   file://3b/sstate:gcc::5.2.0:r0::3:3bb8ffd234f7eb3709b5447f1f82d6d0_populate_lic.tgz.siginfo,
   attempting MIRRORS if available

   ERROR: Fetcher failure: Unable to find file
   file://3b/sstate:gcc::5.2.0:r0::3:3bb8ffd234f7eb3709b5447f1f82d6d0_populate_lic.tgz.siginfo
   anywhere. The paths that were searched were:
       /home/alimon/repos/poky/build-x86/sstate-cache
       /home/alimon/repos/poky/build-x86/sstate-cache

Signed-off-by: Aníbal Limón <anibal.limon@linux.intel.com>