perl: partial upgrade from 5.24.1 to 5.26.0
This is compilation issue obseved

															  DEBUG: Executing shell function do_compile
															  NOTE: make -j 88 -e MAKEFLAGS= perl LD=i586-poky-linux-gcc  -m32 -march=i586 --sysroot=/home/lsandov1/poky-testing/poky-perl-upgrade-5.26/build/tmp/work/i586-poky-linux/perl/5.26.0-r0/recipe-sysroot
															  Perl cross-build directory is /home/lsandov1/poky-testing/poky-perl-upgrade-5.26/build/tmp/work/i586-poky-linux/perl/5.26.0-r0/perl-5.26.0/Cross
															  Target arch is i586-linux
															  toolchain: i586-poky-linux-gcc -m32 -march=i586 --sysroot=/home/lsandov1/poky-testing/poky-perl-upgrade-5.26/build/tmp/work/i586-poky-linux/perl/5.26.0-r0/recipe-sysroot, i586-poky-linux-g++ -m32 -march=i586 --sysroot=/home/lsandov1/poky-testing/poky-perl-upgrade-5.26/build/tmp/work/i586-poky-linux/perl/5.26.0-r0/recipe-sysroot, i586-poky-linux-gcc -m32 -march=i586 --sysroot=/home/lsandov1/poky-testing/poky-perl-upgrade-5.26/build/tmp/work/i586-poky-linux/perl/5.26.0-r0/recipe-sysroot, i586-poky-linux-strip, i586-poky-linux-ar, i586-poky-linux-ranlib
															  Optimizations: -fexpensive-optimizations -fomit-frame-pointer -O2
															  /home/lsandov1/poky-testing/poky-perl-upgrade-5.26/build/tmp/work/i586-poky-linux/perl/5.26.0-r0/perl-5.26.0/Cross/generate_config_sh config.sh-i586-linux > /home/lsandov1/poky-testing/poky-perl-upgrade-5.26/build/tmp/work/i586-poky-linux/perl/5.26.0-r0/perl-5.26.0/Cross/../config.sh
															  cd /home/lsandov1/poky-testing/poky-perl-upgrade-5.26/build/tmp/work/i586-poky-linux/perl/5.26.0-r0/perl-5.26.0/Cross/.. ; ./Configure -S ; make depend ; make ; make more

															  Fetching answers from config.sh...

															  Doing variable substitutions on .SH files...
															  Extracting config.h (with variable substitutions)
															  cflags.SH: cc       = i586-poky-linux-gcc  -m32 -march=i586 --sysroot=/home/lsandov1/poky-testing/poky-perl-upgrade-5.26/build/tmp/work/i586-poky-linux/perl/5.26.0-r0/recipe-sysroot
															  cflags.SH: ccflags  =  -O2 -pipe -g -feliminate-unused-debug-types -fdebug-prefix-map=/home/lsandov1/poky-testing/poky-perl-upgrade-5.26/build/tmp/work/i586-poky-linux/perl/5.26.0-r0=/usr/src/debug/perl/5.26.0-r0 -fdebug-prefix-map=/home/lsandov1/poky-testing/poky-perl-upgrade-5.26/build/tmp/work/i586-poky-linux/perl/5.26.0-r0/recipe-sysroot-native= -fdebug-prefix-map=/home/lsandov1/poky-testing/poky-perl-upgrade-5.26/build/tmp/work/i586-poky-linux/perl/5.26.0-r0/recipe-sysroot=  -DDEBIAN -D_REENTRANT -D_GNU_SOURCE -fwrapv -fno-strict-aliasing -pipe -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -D_FORTIFY_SOURCE=2
															  cflags.SH: stdflags =
															  cflags.SH: optimize = -O2
															  cflags.SH: warn     =  -Wall
															  Extracting cflags (with variable substitutions)
															  Not re-extracting config.h
															  Extracting makedepend (with variable substitutions)
															  linux libraries overwritten by cross-compile patches
															  Extracting Makefile (with variable substitutions)
															  Extracting myconfig (with variable substitutions)
															  Extracting pod/Makefile (with variable substitutions)
															  Extracting Policy.sh (with variable substitutions)
															  Extracting runtests (with variable substitutions)
															  Extraction done.
															  make[1]: Entering directory '/home/lsandov1/poky-testing/poky-perl-upgrade-5.26/build/tmp/work/i586-poky-linux/perl/5.26.0-r0/perl-5.26.0'
															  i586-poky-linux-gcc -m32 -march=i586 --sysroot=/home/lsandov1/poky-testing/poky-perl-upgrade-5.26/build/tmp/work/i586-poky-linux/perl/5.26.0-r0/recipe-sysroot -c -DPERL_CORE -O2 -pipe -g -feliminate-unused-debug-types -fdebug-prefix-map=/home/lsandov1/poky-testing/poky-perl-upgrade-5.26/build/tmp/work/i586-poky-linux/perl/5.26.0-r0=/usr/src/debug/perl/5.26.0-r0 -fdebug-prefix-map=/home/lsandov1/poky-testing/poky-perl-upgrade-5.26/build/tmp/work/i586-poky-linux/perl/5.26.0-r0/recipe-sysroot-native= -fdebug-prefix-map=/home/lsandov1/poky-testing/poky-perl-upgrade-5.26/build/tmp/work/i586-poky-linux/perl/5.26.0-r0/recipe-sysroot= -DDEBIAN -D_REENTRANT -D_GNU_SOURCE -fwrapv -fno-strict-aliasing -pipe -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -D_FORTIFY_SOURCE=2 -O2 -Wall -fPIC generate_uudmap.c
															  gcc  -o generate_uudmap generate_uudmap.c
															  ./generate_uudmap uudmap.h bitcount.h mg_data.h
															  sh ./makedepend MAKE="make" cflags
															  make[2]: Entering directory '/home/lsandov1/poky-testing/poky-perl-upgrade-5.26/build/tmp/work/i586-poky-linux/perl/5.26.0-r0/perl-5.26.0'
															  rm -f opmini.c
															  /bin/ln -s op.c opmini.c
															  rm -f perlmini.c
															  /bin/ln -s perl.c perlmini.c
															  echo av.c scope.c op.c doop.c doio.c dump.c gv.c hv.c mg.c reentr.c mro_core.c perl.c perly.c pp.c pp_hot.c pp_ctl.c pp_sys.c regcomp.c regexec.c utf8.c sv.c taint.c toke.c util.c deb.c run.c universal.c pad.c globals.c keywords.c perlio.c perlapi.c numeric.c mathoms.c locale.c pp_pack.c pp_sort.c caretx.c dquote.c time64.c  miniperlmain.c opmini.c perlmini.c | tr ' ' '\n' >.clist
															  make[2]: Leaving directory '/home/lsandov1/poky-testing/poky-perl-upgrade-5.26/build/tmp/work/i586-poky-linux/perl/5.26.0-r0/perl-5.26.0'
															  Finding dependencies for av.o
															  Finding dependencies for scope.o
															  Finding dependencies for op.o
															  Finding dependencies for doop.o
															  Finding dependencies for doio.o
															  Finding dependencies for dump.o
															  Finding dependencies for gv.o
															  Finding dependencies for hv.o
															  Finding dependencies for mg.o
															  Finding dependencies for reentr.o
															  Finding dependencies for mro_core.o
															  Finding dependencies for perl.o
															  Finding dependencies for perly.o
															  Finding dependencies for pp.o
															  Finding dependencies for pp_hot.o
															  Finding dependencies for pp_ctl.o
															  Finding dependencies for pp_sys.o
															  Finding dependencies for regcomp.o
															  Finding dependencies for regexec.o
															  Finding dependencies for utf8.o
															  Finding dependencies for sv.o
															  Finding dependencies for taint.o
															  Finding dependencies for toke.o
															  Finding dependencies for util.o
															  Finding dependencies for deb.o
															  Finding dependencies for run.o
															  Finding dependencies for universal.o
															  Finding dependencies for pad.o
															  Finding dependencies for globals.o
															  Finding dependencies for keywords.o
															  Finding dependencies for perlio.o
															  Finding dependencies for perlapi.o
															  Finding dependencies for numeric.o
															  Finding dependencies for mathoms.o
															  Finding dependencies for locale.o
															  Finding dependencies for pp_pack.o
															  Finding dependencies for pp_sort.o
															  Finding dependencies for caretx.o
															  Finding dependencies for dquote.o
															  Finding dependencies for time64.o
															  Finding dependencies for miniperlmain.o
															  Finding dependencies for opmini.o
															  Finding dependencies for perlmini.o
															  Updating makefile...
															  make[1]: Leaving directory '/home/lsandov1/poky-testing/poky-perl-upgrade-5.26/build/tmp/work/i586-poky-linux/perl/5.26.0-r0/perl-5.26.0'
															  make[1]: Entering directory '/home/lsandov1/poky-testing/poky-perl-upgrade-5.26/build/tmp/work/i586-poky-linux/perl/5.26.0-r0/perl-5.26.0'
															  echo @`sh  cflags "optimize='-O2'" opmini.o` -fPIC -DPERL_IS_MINIPERL -DPERL_EXTERNAL_GLOB opmini.c
															  @i586-poky-linux-gcc -m32 -march=i586 --sysroot=/home/lsandov1/poky-testing/poky-perl-upgrade-5.26/build/tmp/work/i586-poky-linux/perl/5.26.0-r0/recipe-sysroot -c -DPERL_CORE -O2 -pipe -g -feliminate-unused-debug-types -fdebug-prefix-map=/home/lsandov1/poky-testing/poky-perl-upgrade-5.26/build/tmp/work/i586-poky-linux/perl/5.26.0-r0=/usr/src/debug/perl/5.26.0-r0 -fdebug-prefix-map=/home/lsandov1/poky-testing/poky-perl-upgrade-5.26/build/tmp/work/i586-poky-linux/perl/5.26.0-r0/recipe-sysroot-native= -fdebug-prefix-map=/home/lsandov1/poky-testing/poky-perl-upgrade-5.26/build/tmp/work/i586-poky-linux/perl/5.26.0-r0/recipe-sysroot= -DDEBIAN -D_REENTRANT -D_GNU_SOURCE -fwrapv -fno-strict-aliasing -pipe -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -D_FORTIFY_SOURCE=2 -O2 -Wall -fPIC -DPERL_IS_MINIPERL -DPERL_EXTERNAL_GLOB opmini.c
															  In file included from perl.h:28:0,
															                   from op.c:163:
															  config.h:1962:3: error: invalid preprocessing directive #LONG_DOUBLE_STYLE_IEEE
															   # LONG_DOUBLE_STYLE_IEEE
															     ^~~~~~~~~~~~~~~~~~~~~~
															  config.h:1963:3: error: invalid preprocessing directive #LONG_DOUBLE_STYLE_IEEE_DOUBLEDOUBLE
															   # LONG_DOUBLE_STYLE_IEEE_DOUBLEDOUBLE
															     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
															  config.h:1964:3: error: invalid preprocessing directive #LONG_DOUBLE_STYLE_IEEE_EXTENDED
															   # LONG_DOUBLE_STYLE_IEEE_EXTENDED
															     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
															  config.h:1965:3: error: invalid preprocessing directive #LONG_DOUBLE_STYLE_IEEE_STD
															   # LONG_DOUBLE_STYLE_IEEE_STD
															     ^~~~~~~~~~~~~~~~~~~~~~~~~~
															  config.h:1966:3: error: invalid preprocessing directive #LONG_DOUBLE_STYLE_VAX
															   # LONG_DOUBLE_STYLE_VAX
															     ^~~~~~~~~~~~~~~~~~~~~
															  In file included from perl.h:28:0,
															                   from op.c:163:
															  config.h:2890:3: error: invalid preprocessing directive #HAS_GAI_STRERROR
															   # HAS_GAI_STRERROR /**/
															     ^~~~~~~~~~~~~~~~
															  config.h:3269:3: error: invalid preprocessing directive #HAS_QUERYLOCALE
															   # HAS_QUERYLOCALE /**/
															     ^~~~~~~~~~~~~~~
															  config.h:3270:3: error: invalid preprocessing directive #I_XLOCALE
															   # I_XLOCALE               /**/
															     ^~~~~~~~~
															  config.h:3529:3: error: invalid preprocessing directive #HAS_STRERROR_L
															   # HAS_STRERROR_L  /**/
															     ^~~~~~~~~~~~~~
															  config.h:3714:3: error: invalid preprocessing directive #DEFAULT_INC_EXCLUDES_DOT
															   # DEFAULT_INC_EXCLUDES_DOT /**/
															     ^~~~~~~~~~~~~~~~~~~~~~~~
															  config.h:4048:3: error: invalid preprocessing directive #DOUBLE_HAS_INF
															   # DOUBLE_HAS_INF
															     ^~~~~~~~~~~~~~
															  config.h:4049:3: error: invalid preprocessing directive #DOUBLE_HAS_NAN
															   # DOUBLE_HAS_NAN
															     ^~~~~~~~~~~~~~
															  config.h:4050:3: error: invalid preprocessing directive #DOUBLE_HAS_NEGATIVE_ZERO
															   # DOUBLE_HAS_NEGATIVE_ZERO
															     ^~~~~~~~~~~~~~~~~~~~~~~~
															  config.h:4051:3: error: invalid preprocessing directive #DOUBLE_HAS_SUBNORMALS
															   # DOUBLE_HAS_SUBNORMALS
															     ^~~~~~~~~~~~~~~~~~~~~
															  config.h:4052:3: error: invalid preprocessing directive #DOUBLE_STYLE_CRAY
															   # DOUBLE_STYLE_CRAY
															     ^~~~~~~~~~~~~~~~~
															  config.h:4053:3: error: invalid preprocessing directive #DOUBLE_STYLE_IBM
															   # DOUBLE_STYLE_IBM
															     ^~~~~~~~~~~~~~~~
															  config.h:4054:3: error: invalid preprocessing directive #DOUBLE_STYLE_IEEE
															   # DOUBLE_STYLE_IEEE
															     ^~~~~~~~~~~~~~~~~
															  config.h:4055:3: error: invalid preprocessing directive #DOUBLE_STYLE_VAX
															   # DOUBLE_STYLE_VAX
															     ^~~~~~~~~~~~~~~~
															  makefile:312: recipe for target 'opmini.o' failed
															  make[1]: *** [opmini.o] Error 1
															  make[1]: Leaving directory '/home/lsandov1/poky-testing/poky-perl-upgrade-5.26/build/tmp/work/i586-poky-linux/perl/5.26.0-r0/perl-5.26.0'
															  make[1]: Entering directory '/home/lsandov1/poky-testing/poky-perl-upgrade-5.26/build/tmp/work/i586-poky-linux/perl/5.26.0-r0/perl-5.26.0'
															  rm -f pod/perl5260delta.pod
															  /bin/ln -s perldelta.pod pod/perl5260delta.pod
															  ./miniperl -Ilib autodoc.pl
															  make[1]: ./miniperl: Command not found
															  makefile:421: recipe for target 'pod/perlintern.pod' failed
															  make[1]: *** [pod/perlintern.pod] Error 127
															  make[1]: Leaving directory '/home/lsandov1/poky-testing/poky-perl-upgrade-5.26/build/tmp/work/i586-poky-linux/perl/5.26.0-r0/perl-5.26.0'
															  Makefile:37: recipe for target 'perl' failed
															  make: *** [perl] Error 2
															  ERROR: oe_runmake failed
															  WARNING: /home/lsandov1/poky-testing/poky-perl-upgrade-5.26/build/tmp/work/i586-poky-linux/perl/5.26.0-r0/temp/run.do_compile.157830:1 exit 1 from 'exit 1'
															  ERROR: Function failed: do_compile (log file is located at /home/lsandov1/poky-testing/poky-perl-upgrade-5.26/build/tmp/work/i586-poky-linux/perl/5.26.0-r0/temp/log.do_compile.157830)

Signed-off-by: Leonardo Sandoval <leonardo.sandoval.gonzalez@linux.intel.com>