gpp_sign: improve subprocess call when signing packages
The rpmsign command formed to sign packages is a single string
thus it must to be executed using shell=True according to the python
documentation. Without this change, the rpmsign command silently failed
with the error below and subprocess call never comes back
(end--of-file never yield by the rpmsign?):

Exception: FileNotFoundError: [Errno 2] No such file or directory: ".../tmp/work/i586-poky-linux/ed/1.14.2-r0/recipe-sysroot-native/usr/bin/rpmsign --addsign --define '_gpg_name testuser'  --define '_gpg_sign_cmd_extra_args --no-permission-warning --batch --passphrase=test123 --pinentry-mode=loopback' --define '_binary_filedigest_algorithm 8' --define '__gpg .../tmp/hosttools/gpg' --define '_gpg_path /tmp/oeqa-signing-xc4tqgkp' .../tmp/work/i586-poky-linux/ed/1.14.2-r0/deploy-rpms/i586/ed-doc-1.14.2-r0.i586.rpm .../tmp/work/i586-poky-linux/ed/1.14.2-r0/deploy-rpms/i586/ed-1.14.2-r0.i586.rpm .../tmp/work/i586-poky-linux/ed/1.14.2-r0/deploy-rpms/i586/ed-dbg-1.14.2-r0.i586.rpm .../tmp/work/i586-poky-linux/ed/1.14.2-r0/deploy-rpms/i586/ed-dev-1.14.2-r0.i586.rpm"

[YOCTO #12022]

Signed-off-by: Leonardo Sandoval <leonardo.sandoval.gonzalez@linux.intel.com>