Revert "scripts: Add symlink to real utils (perf optimise experiment)"
This reverts commit a8e322a4c030f1d61e4f3049734932bb2e6f3887.

Breaks ESDK:

ERROR:  OE-core's config sanity checker detected a potential misconfiguration.
    Either fix the cause of this error or at your own risk disable the checker (see sanity.conf).
    Following is the list of potential problems / advisories:

    Your gcc version is older than 4.5 or is not working properly.  Please verify you can build and link something that uses atomic operations, such as:
        __sync_bool_compare_and_swap (&atomic, 2, 3);