selinux_common: remove EXTRA_OEMAKE = "-e"
Some variables are exported by top Makefile and updated from sub
Makefile (such as PCRE_LDFLAGS, DISABLE_FLAGS ...).

The '-e' option prevents those variables from updating in the sub
Makefile and causes libselinux build errors:

| label.lo:(.data.rel.ro.local+0x20): undefined reference to `selabel_property_init'
| label.lo:(.data.rel.ro.local+0x28): undefined reference to `selabel_service_init'

oe-core also cleaned such default value from commit: aeb65386

Signed-off-by: Wenzong Fan <wenzong.fan@windriver.com>