debugedit: Fix install conflict when enable multilib.
Error: Transaction test error:
  file /usr/bin/find-debuginfo conflicts between attempted installs of debugedit-5.1-r0.core2_64 and lib32-debugedit-5.1-r0.core2_32

The differences of find-debuginfo are as follows:

@@ -360,7 +360,7 @@ add_minidebug()
   # symbol and NOBITS sections so cannot use --keep-only because that is
   # too aggressive. Field $2 is the section name, $3 is the section type
   # and $8 are the section flags.
-  local remove_sections=`x86_64-poky-linux-readelf -W -S "$debuginfo" \
+  local remove_sections=`i686-pokymllib32-linux-readelf -W -S "$debuginfo" \
        | awk '{ if (index($2,".debug_") != 1 \
                     && ($3 == "PROGBITS" || $3 == "NOTE" || $3 == "NOBITS") \
                     && index($8,"A") == 0) \

(From OE-Core rev: a87949a7c207d3d37765229d7772a35a68a27aaf)

Signed-off-by: Wang Mingyu <wangmy@fujitsu.com>
Signed-off-by: Mathieu Dubois-Briand <mathieu.dubois-briand@bootlin.com>