libaio: extend to nativesdk
lvm2 currently requires libaio. So building nativesdk-lvm2 will
result in the following error.

  ERROR: Required build target 'nativesdk-lvm2' has no buildable providers.
  Missing or unbuildable dependency chain was: ['nativesdk-lvm2', 'nativesdk-libaio']

Extend libaio to nativesdk to fix this issue.

Signed-off-by: Chen Qi <Qi.Chen@windriver.com>