parse: add bitbake version check via bitbake_min_version keyword
Layers (e.g. openembedded-core) can specify in conf/layer.conf:

bitbake_min_version 2.15.2

and if bitbake has a lesser version it will stop itself, as early
as possible, to avoid hitting cryptic compatibility issues later on,
with this error:

bb.parse.ParseError: ParseError at /home/alex/bitbake-builds/poky-master-poky-distro_poky-machine_qemux86-64/layers/openembedded-core/meta/conf/layer.conf:1: Bitbake version 2.15.3 is required and version 2.15.2 is used

Note that sanity.bbclass in oe-core has a similar check, but as
this thread [1] highlighted, compatibility issues can stop bitbake
sooner and the check is never reached, leaving the user with
confusing errors.

[1] https://lists.openembedded.org/g/openembedded-core/topic/115724008

Signed-off-by: Alexander Kanavin <alex@linutronix.de>