oeqa/sdk/cases/buildgalculator.py: skip if gettext not available
We need to skip this testcase when gettext is not available. Otherwise,
we will have the following error at configure.

  error: possibly undefined macro: AM_NLS

(From OE-Core rev: ccc10e95c9fcdabcf4ae5e6f9cc34c1d632b4654)

Signed-off-by: Chen Qi <Qi.Chen@windriver.com>
Signed-off-by: Ross Burton <ross.burton@intel.com>
Signed-off-by: Richard Purdie <richard.purdie@linuxfoundation.org>
Signed-off-by: Armin Kuster <akuster808@gmail.com>