utils.bbclass: fix KeyError exception
The following statement was accidently removed. Add it back.

  values['ml'] = ['']

This patch fixes the following error.

  Exception: KeyError: 'ml'

Signed-off-by: Chen Qi <Qi.Chen@windriver.com>