sstatetests: skip allarch_samesigs related tests in case opengl not represet
Two tests (allarch_samesigs and its multilib version) build 'world' in
a multilib setup and some distros, i.e. nodistro, have trouble building it due to missing distro's
features (opengl in this case), thus skip indicated tests otherwise we
see the following errors:

    AssertionError: Command 'bitbake  world meta-toolchain -S none' returned non-zero exit status 1:
    Loading cache...done.
    Loaded 2112 entries from dependency cache.
    NOTE: Resolving any missing task queue dependencies
    ERROR: Nothing PROVIDES 'virtual/lib32-libgl' (but virtual:multilib:lib32:/../meta/recipes-graphics/waffle/waffle_1.5.2.bb DEPENDS on or otherwise requires it). Close matches:
      virtual/lib32-libsdl
      virtual/lib32-libc
      virtual/lib32-libsdl2
    ERROR: Required build target 'lib32-meta-world-pkgdata' has no buildable providers.
    Missing or unbuildable dependency chain was: ['lib32-meta-world-pkgdata', 'meta-world-pkgdata', 'lib32-waffle', 'virtual/lib32-libgl']

[YOCTO #10900]

Signed-off-by: Leonardo Sandoval <leonardo.sandoval.gonzalez@linux.intel.com>