kernelsrc/perf: fix dependency on non existant task when using externalsrc
When externalsrc is enabled for kernel, do_patch doesn't exist since is in
SRCTREECOVEREDTASKS, so make these depend on a real task.

Fixes:
    ERROR: Task do_unpack in /data/yocto/poky/meta/recipes-kernel/perf/perf.bb
    depends upon non-existent task do_patch in /data/yocto/poky/meta/recipes-kernel/linux/linux-yocto_4.8.bb

Signed-off-by: Stefan Stanacar <sstncr@gmail.com>
Signed-off-by: Joshua Watt <JPEWhacker@gmail.com>