layer.conf: Add xserver-nodm-init to SIGGEN_EXCLUDERECIPES_ABISAFE
Found signature differences when same machine is used as a copy
see

ERROR: xscreensaver different signature for task do_package_write_ipk.sigdata between qemux86copy and qemux86
Hash for dependent task x11-common/xserver-nodm-init_3.0.bb:do_packagedata changed from de0944d4fcaeed0efdb143a18cc406bd043469ae291de1704a999bc878a7691c to ba7bdaf35860ba5bf5a5f4ce06379a77c88eb9806e09a1fc5373933888a46507

(From OE-Core rev: 7f44cdd146036845e2f71f92d75c1222aa7c6d9b)

Signed-off-by: Khem Raj <raj.khem@gmail.com>
Signed-off-by: Ross Burton <ross.burton@intel.com>
Signed-off-by: Richard Purdie <richard.purdie@linuxfoundation.org>