pseudo: Fix compile error on centos7
When host is centos7, fix the following build errors:

In file included from pseudolog.c:21:
/usr/include/sys/stat.h:366:31: error: array type has incomlete element type

In file included from pseudolog.c:21:
/usr/include/sys/stat.h:366:31: error: array type has incomplete element type "struct timespec"
  366 |         const struct timespec __times[2],
      |                               ^~~~~~~
pseudolog.c: In function "parse_file_type":
pseudolog.c:214:10: error: "S_IFSOCK" undeclared (first use in this function)
  214 |   return S_IFSOCK;
      |          ^~~~~~~~
pseudolog.c: In function "format_one":
pseudolog.c:754:43: error: "ALLPERM"  undeclared (first use in this function)
  754 |   printf(fmtbuf, (unsigned int) e->mode & ALLPERMS);
      |                                           ^~~~~~~~

upstream commit:
https://git.yoctoproject.org/pseudo/commit/?id=15b4f4ca25593f684e6517d0b809605b443d1953
When the host is older system,such as centos7, this upstream commit will introduce
the build errors. To add "#define _BSD_SOURCE" is mainly to avoid issues on older
systems that do not recognize _DEFAULT_SOURCE.

(From OE-Core rev: 32b21afbe7d468db787ec7e8d93a5e211976eef5)

Signed-off-by: Guocai He <guocai.he.cn@windriver.com>
Signed-off-by: Steve Sakoman <steve@sakoman.com>