oeqa/sdk/cases/buildgalculator.py: skip if gettext not available
We need to skip this testcase when gettext is not available. Otherwise,
we will have the following error at configure.

  error: possibly undefined macro: AM_NLS

Signed-off-by: Chen Qi <Qi.Chen@windriver.com>