oeqa: Use --disable-maintainer-mode configure option
since the versions of autotools might differ, and difference in
timestamps for configure and system can result in reconfigure lets avoid
that by telling configure to ignore such differences.

Avoids
error: newly created file is older than distributed files!

[YOCTO #13779]

Suggested-by: Andre McCurdy <armccurdy@gmail.com>
Signed-off-by: Khem Raj <raj.khem@gmail.com>
Signed-off-by: Richard Purdie <richard.purdie@linuxfoundation.org>