bbtests.py: use IMAGE_NAME instead of IMAGE_LINK_NAME when looking for manifest
* IMAGE_LINK_NAME can now contain DATE and get_bb_vars()
  might return different value in the test compared to
  when the image was actually being built and manifest created

* fixes:
  2022-06-09 16:56:04,166 - oe-selftest - INFO - test_image_manifest (bbtests.BitbakeTests.test_image_manifest)
  2022-06-09 17:29:36,033 - oe-selftest - INFO -  ... FAIL
  2022-06-09 17:29:36,034 - oe-selftest - INFO - Traceback (most recent call last):
    File "/OE/build/poky/meta/lib/oeqa/selftest/cases/bbtests.py", line 137, in test_image_manifest
      self.assertTrue(os.path.islink(manifest), msg="No manifest file created for image. It should have been created in %s" % manifest)
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  AssertionError: False is not true : No manifest file created for image. It should have been created in /OE/build/poky/build-st/tmp/deploy/images/qemux86-64/core-image-minimal-qemux86-64-1.0-r0-20220609152931.manifest

  when:
37903875 -rw-r--r-- 4 martin martin 193K Jun  9 17:29 /OE/build/poky/build-st/tmp/deploy/images/qemux86-64/core-image-minimal-qemux86-64-1.0-r0-20220609145610.testdata.json
37903875 -rw-r--r-- 4 martin martin 193K Jun  9 17:29 /OE/build/poky/build-st/tmp/deploy/images/qemux86-64/core-image-minimal-qemux86-64.rootfs.testdata.json
37903876 -rw-r--r-- 4 martin martin 1.1K Jun  9 17:29 /OE/build/poky/build-st/tmp/deploy/images/qemux86-64/core-image-minimal-qemux86-64-1.0-r0-20220609145610.manifest
37903876 -rw-r--r-- 4 martin martin 1.1K Jun  9 17:29 /OE/build/poky/build-st/tmp/deploy/images/qemux86-64/core-image-minimal-qemux86-64.rootfs.manifest
37903877 -rw-r--r-- 4 martin martin 1.5K Jun  9 17:29 /OE/build/poky/build-st/tmp/deploy/images/qemux86-64/core-image-minimal-qemux86-64-1.0-r0-20220609145610.qemuboot.conf
37903877 -rw-r--r-- 4 martin martin 1.5K Jun  9 17:29 /OE/build/poky/build-st/tmp/deploy/images/qemux86-64/core-image-minimal-qemux86-64.rootfs.qemuboot.conf
37903879 -rw-r--r-- 4 martin martin  13M Jun  9 17:29 /OE/build/poky/build-st/tmp/deploy/images/qemux86-64/core-image-minimal-qemux86-64-1.0-r0-20220609145610.tar.bz2
37903879 -rw-r--r-- 4 martin martin  13M Jun  9 17:29 /OE/build/poky/build-st/tmp/deploy/images/qemux86-64/core-image-minimal-qemux86-64.rootfs.tar.bz2
37903880 -rw-r--r-- 4 martin martin  27M Jun  9 17:29 /OE/build/poky/build-st/tmp/deploy/images/qemux86-64/core-image-minimal-qemux86-64-1.0-r0-20220609145610.ext4
37903880 -rw-r--r-- 4 martin martin  27M Jun  9 17:29 /OE/build/poky/build-st/tmp/deploy/images/qemux86-64/core-image-minimal-qemux86-64.rootfs.ext4

  i.e. all artifacts were created with 1.0-r0-20220609145610 IMAGE_SUFFIX hardlinks
  but the test looks for 1.0-r0-20220609152931

Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>