oe-init-build-env: define umask
If umask is not suitable for bitbake it terminates with:
  ERROR:  OE-core's config sanity checker detected a potential
    misconfiguration.
    Either fix the cause of this error or at your own risk disable
    the checker (see sanity.conf). Following is the list of potential
    problems / advisories:
    Please use a umask which allows a+rx and u+rwx

Set the umask flags in the oe-init-build-env script to prevent from this
error.

Signed-off-by: Adrian Freihofer <adrian.freihofer@siemens.com>