dbus: upgrade to 1.12.2
1. os-test.patch is removed because current dbus has removed
   distro specific init script.

2. Add autoconf-archive to DEPENDS to fix do_configure failure as below.
     error: Unexpanded AX_ macro found.

3. Modify FILES variable to fix installed-vs-shipped QA issue.

Signed-off-by: Chen Qi <Qi.Chen@windriver.com>