rust: Upgrade 1.85.1->1.86.0
* Add pkgconfig-native and openssl to resolve openssl-sys crate
dependency on pkg-config. The exact commit was not found found, but the
crate's document mentions it as the required dependecy.

| error: failed to run custom build command for `openssl-sys v0.9.106`
| Could not find openssl via pkg-config:
|   The pkg-config command could not be found.
|
|   Most likely, you need to install a pkg-config package for your OS.
|   Try `apt install pkg-config`, or `yum install pkg-config`,
|   or `pkg install pkg-config`, or `apk add pkgconfig` depending on your distribution

https://crates.io/crates/openssl-sys/0.9.108/dependencies
https://github.com/rust-lang/rust/blob/master/INSTALL.md#dependencies

* Add Ninja as a dependency for building Rust to prevent bootstrap build regression.

Fixes:
| Building LLD for x86_64-unknown-linux-gnu
|
| Couldn't find required command: ninja (or ninja-build)
|
| You should install ninja as described at
| <https://github.com/ninja-build/ninja/wiki/Pre-built-Ninja-packages>,
| or set `ninja = false` in the `[llvm]` section of `config.toml`.
| Alternatively, set `download-ci-llvm = true` in that `[llvm]` section
| to download LLVM rather than building it.

* Add bash to DEPENDS to resolve missing dependency for subtree-sync.sh
Fixes:
ERROR: rust-1.86.0-r0 do_package_qa: QA Issue: /usr/lib/rustlib/src/rust/library/portable-simd/subtree-sync.sh
contained in package rust requires /bin/bash, but no providers found in RDEPENDS:rust? [file-rdeps]

* Add do_install:append() task to remove cargo bin from rust native builds.
This resolves the following conflict:

Fixes:
ERROR: libstd-rs-1.86.0-r0 do_prepare_recipe_sysroot: The file /usr/bin/cargo is
installed by both rust-native and cargo-native, aborting

* Update Unicode-3.0 license checksums.
License-Update: Copyright and license files to distributions are updated.

https://github.com/rust-lang/rust/commit/f9c16997dc016a3ef1456f56df2ab564a1c48cb2
  It adds copyright and license files (including HTML versions) to distributions,
  aligns with license compliance tools like reuse, and ensures all required
  license texts are properly included and formatted.

* The "remote-test-server" bin is now generated in stage2-tools-bin dir rather than stage1.
  Update the test suite accordingly.

* Fix do_package QA issue by packing missing zsh files and directories:

Fixes:
do_package: QA Issue: rust: Files/directories were installed but not shipped in any package:
/usr/share/zsh
/usr/share/zsh/site-functions
/usr/share/zsh/site-functions/_cargo
Please set FILES such that these items are packaged. Alternatively if they are unneeded,
avoid installing them or delete them within do_install

* Install "llvm-tblgen" from native-sysroot to recipe sysroot to handle
  file not found error during rust builds:

Fixes:
/bin/sh: line 1:/home/poky/build/tmp/work/core2-64-poky-linux/rust/1.86.0/recipe-sysroot/usr/lib/llvm-rust/bin/llvm-tblgen:
No such file or directory

| make[2]: *** [COFF/CMakeFiles/COFFOptionsTableGen.dir/build.make:120: COFF/Options.inc] Error 127
| make[1]: *** [CMakeFiles/Makefile2:630: COFF/CMakeFiles/COFFOptionsTableGen.dir/all] Error 2
| make[1]: *** Waiting for unfinished jobs....

* Enable INHIBIT_PACKAGE_DEBUG_SPLIT/STRIP to fix QA stripping errors.

Fixes:
ERROR: rust-1.86.0-r0 do_package: QA Issue: File '/usr/lib/rustlib/x86_64-poky-linux-gnu/bin/wasm-component-ld'
from rust was already stripped, this will prevent future debugging! [already-stripped]

* Some Rust files result in ELF binary with GNU_HASH.
 Add ldflags to INSANE_SKIP ignore the error:

do_package_qa: QA Issue: File /usr/lib/rustlib/x86_64-poky-linux-gnu/bin/rust-lld
in package rust doesn't have GNU_HASH (didn't pass LDFLAGS?) [ldflags]

* Drop Zdual-proc-macros-additional-check.patch patch
 since it's merged with v1.86.0
 https://github.com/rust-lang/rust/commit/139d6ba054a1a4cc5fe64981ad46fd5547bd4916

* LTO config is applied to rustdoc from v1.86.0.
 Rebase 0001-src-core-build_steps-tool.rs-switch-off-lto-for-rust.patch
 which disables it to avoid suffixes in binaries causing non-reproducibility.
 https://github.com/rust-lang/rust/commit/1fe351b

 Note: Need to verify if the patch is still necessary through reproducibility testing.
 (reminder for me: Reproducibility tests to be done and add again dropped
  repro-issue-fix-with-cc-crate-hashmap.patch, if required.)

Signed-off-by: Yash Shinde <Yash.Shinde@windriver.com>
Signed-off-by: Harish Sadineni <Harish.Sadineni@windriver.com>