devtool.py: remove fetch results from download directory to avoid failure
The fetch results need to be removed from the download directory to avoid
failures like below.

  Submodule path 'doxyport': checked out 'db3e1a6eb8677d3166d90d82c3068689803ce547'

  fatal: reference is not a tree: 67cad692720982ac3cbd99bf1c3421edc69b08f9
  Unable to checkout '67cad692720982ac3cbd99bf1c3421edc69b08f9' in submodule path 'doxygen2jsdoc'

  ERROR: Function failed: base_do_unpack

Signed-off-by: Chen Qi <Qi.Chen@windriver.com>