recipetool: create: do not treat numbers in scm URLs as versions
Numbers within SCM URLs are extremely unlikely to be valid version
numbers - more likely they are just part of the name, so don't try to
extract them and use them as the version.

Doing so causes pretty bad behaviour within devtool:

--------- snip ---------
$ devtool add https://github.com/inhedron/libtr50
NOTE: Fetching git://github.com/inhedron/libtr50;protocol=https...
...
NOTE: Using default source tree path .../build/workspace/sources/libtr
...
RecursionError: maximum recursion depth exceeded while calling a Python object
--------- snip ---------

(This was because ${PV} was being substituted into the URL, but PV's
value was being set to include ${SRCPV}, so there was a circular
reference.)

Signed-off-by: Paul Eggleton <paul.eggleton@linux.intel.com>